server:
  port: 8000

spring:
  application:
    name: ORDER

  #数据库配置
  datasource:  #3306后面的是Mysql中数据库的名称不是表的
    url: jdbc://mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接池
    type: com.alibaba.druid.pool.DruidDataSource

#eureka注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/

#mybatis
#扫描实体类的所在包
mybatis:
  type-aliases-package: com.example.demo.pojo
  #mapper接口对应的.xml文件
  mapper-locations:
    classpath: mapper/*.xml
  config-location:
    classpath: mybatis/mybatis-config.xml


#通用mapper的所在接口名称(不是业务的mapper) ,不只是包名
mapper:
  mappers: com.example.demo.mapper.MyMapper
  identity: MYSQL

